spring:
  application:
    name: paymelavo
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
        pool-name: paymelavo-pool
        maximum-pool-size: 10
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update           # schema is owned by Flyway; Hibernate only validates
    properties:
      hibernate:
        jdbc.time_zone: UTC